export const SHAPES_FETCH_SUCCESS = "SHAPES_FETCH_SUCCESS";
export const SHAPES_FETCH_FAILURE = "SHAPES_FETCH_FAILURE";

export const SHAPE_MOVE_START = "SHAPE_MOVE_START";
export const SHAPE_MOVE_SUCCESS = "SHAPE_MOVE_SUCCESS";
export const SHAPE_MOVE_END = "SHAPE_MOVE_END";
